apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u3wv22ptx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u3wv22ptx-go 
  name: u3wv22ptx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u3wv22ptx-go 
